---
- name: Create proxmox instances
  tags: proxmox-create-instance
  vars:
    _create_config: &_create_config
      hostname: "{{ instance.hostname }}"
      password: "{{ instance.host_password | d(omit) }}"
      pubkey: "{{ lookup('ansible.builtin.file', instance.identity_file ~ '.pub') }}"
      ostemplate: "{{ instance.ostemplate }}"
      storage: "{{ instance.storage | d(omit) }}"
      disk: "{{ instance.disk | d(omit) }}"
      disk_volume: "{{ instance.disk_volume | d(omit) }}"
      cores: "{{ instance.cores | d(omit) }}"
      memory: "{{ instance.memory | d(omit) }}"
      swap: "{{ instance.swap | d(omit) }}"
      onboot: "{{ instance.onboot | d(omit) }}"
      hookscript: "{{ instance.hookscript | d(omit) }}"
      tags: "{{ instance.tags | d(omit) }}"
      netif: "{{ instance.netif | d({'net0': {'name': 'eth0', 'ip': 'dhcp', 'bridge': 'vmbr0', 'firewall': '1'}}) }}"
      features:
        - nesting=1
  notify: Proxmox changed
  block:
    - name: Show the instance
      ansible.builtin.debug:
        var: instance
      loop_control:
        loop_var: instance

    - name: If instance type is clone
      when: "instance.type == 'clone'"
      block:
        - name: Retrieve the clone source
          community.general.proxmox_vm_info:
            type: lxc
            name: "{{ instance.clone_from_name }}"
          retries: 5
          delay: 1
          register: _vm_clone_info

        - name: Reject if we couldn't identify unique template
          ansible.builtin.fail:
            msg: "Couldn't identify unique clone source"
          when: _vm_clone_info.proxmox_vms | length != 1

        - name: Create new linked clone container
          community.general.proxmox:
            hostname: "{{ instance.hostname }}"
            password: "{{ instance.host_password | d(omit) }}"
            pubkey: "{{ lookup('ansible.builtin.file', instance.pubkey) }}"
            clone: "{{ _vm_clone_info.proxmox_vms[0].vmid }}"
            clone_type: linked
            timeout: 120
            storage: ""
          register: _new_clone_vm

    - name: Debug the new clone vm
      ansible.builtin.set_fact:
        clone_config: *_create_config

    - name: Create new standard instance from ostemplate
      when: "instance.type == 'instance'"
      block:
        - name: Create new unlinked container
          community.general.proxmox:
            <<: *_create_config
          register: _new_vm

    - name: Set the new new_vm depending on the type
      ansible.builtin.set_fact:
        new_vm:
          vmid: "{{ _new_vm.vmid | d(_new_clone_vm.vmid) }}"
          changed: "{{ _new_vm.vmid is defined | ternary(_new_vm.changed, _new_clone_vm.changed) }}"

    - name: Retrieve pre-start info
      community.general.proxmox_vm_info:
        type: lxc
        vmid: "{{ new_vm.vmid }}"
        network: true
      retries: 10
      delay: 1
      register: _vm_prestart_info

    - name: Check whether we are trying to start a template
      ansible.builtin.assert:
        that:
          - _vm_prestart_info.proxmox_vms[0].vmid is defined
          - not _vm_prestart_info.proxmox_vms[0].template
        fail_msg: "Cannot start a template"
        success_msg: "Unique vm identified"

    - name: Start the container
      community.general.proxmox:
        vmid: "{{ new_vm.vmid }}"
        state: started
        timeout: 30
      retries: 5
      delay: 1
      register: started_vm

    - name: Retrieve post-start info
      community.general.proxmox_vm_info:
        type: lxc
        vmid: "{{ new_vm.vmid }}"
        network: true
      retries: 10
      delay: 1
      register: _vm_poststart_info
      until:
        - _vm_poststart_info.proxmox_vms[0].status == 'running'
        - _vm_poststart_info.proxmox_vms[0].network | selectattr('name', 'eq', instance.netifname) | list | length > 0
        - _vm_poststart_info.proxmox_vms[0].network | selectattr('name', 'eq', instance.netifname) | selectattr('inet', 'defined') | list | length > 0

    - name: Set fact if eth0 has inet
      ansible.builtin.set_fact:
        address: "{{ _vm_poststart_info.proxmox_vms[0].network |
          selectattr('name', 'eq', instance.netifname) |
          map(attribute='inet') | first | split('/') | first }}"

    - name: Create the result entry
      ansible.builtin.set_fact:
        _result:
          - hostname: "{{ instance.hostname }}"
            address: "{{ address }}"
            user: "{{ instance.host_user }}"
            identity_file: "{{ instance.identity_file }}"
            port: "{{ instance.host_port }}"
            vmid: "{{ new_vm.vmid }}"
            changed: "{{ new_vm.changed or started_vm.changed }}"

    - name: Merge the exist instance infos
      ansible.builtin.set_fact:
        _result: "{{ instance | combine(_result) }}"

    - name: Create the server list
      ansible.builtin.set_fact:
        _server:
          results:
            - "{{ _result }}"

    - name: Merge facts
      ansible.builtin.set_fact:
        server: "{{ server | ansible.builtin.combine(_server, list_merge='append') }}"
