---
- name: Create
  hosts: localhost
  connection: local
  gather_facts: false
  # no_log: "{{ molecule_no_log }}"
  vars:
    _proxmox_changed: false # internal flag for tracking
  handlers:
    - name: Proxmox changed
      ansible.builtin.set_fact:
        _proxmox_changed: true
  tasks:
    - name: Run the create action
      ansible.builtin.include_tasks: tasks/main.yml
      vars:
        proxmox_action: create

    - name: Create instance config
      when: server.changed | default(false) | bool # noqa no-handler
      block:
        - name: Populate instance config dict # noqa jinja
          ansible.builtin.set_fact:
            instance_conf_dict:
              "instance": "{{ item.name }}"
              "address": "{{ item.address }}"
              "user": "{{ item.user }}"
              "port": "{{ item.port }}"
              "vmid": "{{ item.vmid }}"
              "identity_file": "{{ item.identity_file }}"
          with_items: "{{ server.results }}"
          register: instance_config_dict

        - name: Instance_config_dict
          ansible.builtin.debug:
            var: instance_config_dict

        - name: Convert instance config dict to a list
          ansible.builtin.set_fact:
            instance_conf: "{{ instance_config_dict.results | map(attribute='ansible_facts.instance_conf_dict') | list }}"

        - name: Dump instance config
          ansible.builtin.copy:
            content: |
              # Molecule managed

              {{ instance_conf | to_json | from_json | to_yaml }}
            dest: "{{ molecule_instance_config }}"
            mode: "0600"
