---
- name: Destroy
  hosts: localhost
  connection: local
  gather_facts: false
  # no_log: "{{ molecule_no_log }}"
  vars:
    _proxmox_changed: false # internal flag for tracking
  handlers:
    - name: Proxmox changed
      ansible.builtin.set_fact:
        _proxmox_changed: true
  tasks:
    - name: Touch instance config to avoid errors
      ansible.builtin.copy:
        dest: "{{ molecule_instance_config }}"
        content: |
          ---
          # Molecule managed
          []
        mode: "0600"
        force: false

    - name: Read the instance config
      ansible.builtin.slurp:
        src: "{{ molecule_instance_config }}"
      register: _instance_config

    - name: Set the instance config
      ansible.builtin.set_fact:
        _conf: "{{ _instance_config['content'] | b64decode | from_yaml }}"

    - name: Set the instance config
      ansible.builtin.set_fact:
        _instance_conf: "{{ _conf if _conf else [] }}"

    - name: Run the Delete job
      ansible.builtin.include_tasks: tasks/main.yml
      vars:
        proxmox_instances: "{{ _instance_conf }}"
        proxmox_action: destroy

    - name: Populate instance config
      # when: server.changed | default(false) | bool # noqa no-handler
      ansible.builtin.set_fact:
        instance_conf: []

    - name: Dump instance config
      ansible.builtin.copy:
        content: |
          ---
          # Molecule managed

          {{ instance_conf | to_json | from_json | to_nice_yaml }}
        dest: "{{ molecule_instance_config }}"
        mode: "0600"
